# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project3_P2/DSD2_Project3_P2.srcs/sources_1/new/Control_Unit.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/new/full_adder.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/new/ripple_carry.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/new/multiplier.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/notN.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/sllN.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/srlN.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/sraN.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/log_and.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/log_or.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/imports/new/log_xor.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/new/alu4.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project5/bcd_seven_seg_converter.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project5/DSD2_Project5.srcs/sources_1/new/data_memory.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Hw/dsd2_project4/dsd2_project4.srcs/sources_1/new/execute_stage.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project3_P2/reg_file.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project3_P2/DSD2_Project3_P2.srcs/sources_1/new/instruction_decode.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project3/DSD2_Project3.srcs/sources_1/new/instruction_mem.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project3/DSD2_Project3.srcs/sources_1/new/instruction_fetch.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project5/seven_seg_controller.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project5/DSD2_Project5.srcs/sources_1/new/memory_stage.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/imports/Documents/DSD2 Projects/DSD2_Project5/DSD2_Project5.srcs/sources_1/new/writeback_stage.vhd}
  {C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.srcs/sources_1/new/micro_procHW.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/MemoryStageHW.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/MemoryStageHW.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top micro_procHW -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef micro_procHW.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file micro_procHW_utilization_synth.rpt -pb micro_procHW_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
