webtalk_init -webtalk_dir C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 24 17:16:43 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "08b5c22c-7761-45c2-a417-1b552efc1cb1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a7486082ff334885a61be1d7aacb02d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "60" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9200_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3992522012 -regid "" -xml C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Jean-Charles Mve/Documents/DSD2 Hw/DSD2_Project6/DSD2_Project6.sim/sim_1/behav/xsim/xsim.dir/microprocessor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
